#!/usr/bin/env python3
"""build_web_assets.py

Compresses webapp assets (HTML, CSS, JS) with gzip and generates
a C++ header file (firmware/src/network/web_server_content.h) with PROGMEM byte arrays
and route registration helpers for AsyncWebServer.
"""

import gzip
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
WEBAPP_DIR = REPO_ROOT / "webapp"
OUTPUT_HEADER = REPO_ROOT / "firmware" / "src" / "network" / "web_server_content.h"

ASSETS = [
    ("index.html", "/", "text/html"),
    ("css/style.css", "/css/style.css", "text/css"),
    ("js/protocol.js", "/js/protocol.js", "application/javascript"),
    ("js/ws-client.js", "/js/ws-client.js", "application/javascript"),
    ("js/traditional-nav-tab.js", "/js/traditional-nav-tab.js", "application/javascript"),
    ("js/wasd-tab.js", "/js/wasd-tab.js", "application/javascript"),
    ("js/joystick-tab.js", "/js/joystick-tab.js", "application/javascript"),
    ("js/gesture-tab.js", "/js/gesture-tab.js", "application/javascript"),
    ("js/app.js", "/js/app.js", "application/javascript"),
]


def to_c_identifier(name: str) -> str:
    return "WEB_ASSET_" + name.replace("/", "_").replace(".", "_").replace("-", "_").upper()


def main():
    lines = [
        "/**",
        " * @file web_server_content.h",
        " * @brief Autogenerated embedded static web assets for ESP32 HTTP server.",
        " * Generated by firmware/tools/build_web_assets.py.",
        " */",
        "",
        "#ifndef WEB_SERVER_CONTENT_H",
        "#define WEB_SERVER_CONTENT_H",
        "",
        "#include <Arduino.h>",
        "#include <ESPAsyncWebServer.h>",
        "",
    ]

    route_registrations = []

    for rel_path, route, mime in ASSETS:
        file_path = WEBAPP_DIR / rel_path
        if not file_path.exists():
            print(f"Error: Asset not found: {file_path}")
            return 1

        raw_data = file_path.read_bytes()
        gz_data = gzip.compress(raw_data, compresslevel=9)
        c_name = to_c_identifier(rel_path)

        lines.append(f"// {rel_path}: {len(raw_data)} bytes -> {len(gz_data)} bytes gzipped")
        lines.append(f"const size_t {c_name}_LEN = {len(gz_data)};")
        lines.append(f"const uint8_t {c_name}_GZ[] PROGMEM = {{")

        # Format hex bytes in chunks of 16
        for i in range(0, len(gz_data), 16):
            chunk = gz_data[i : i + 16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            lines.append(f"    {hex_str},")
        lines.append("};")
        lines.append("")

        route_registrations.append(
            f'    server->on("{route}", HTTP_GET, [](AsyncWebServerRequest *request) {{\n'
            f'        AsyncWebServerResponse *response = request->beginResponse(200, "{mime}", {c_name}_GZ, {c_name}_LEN);\n'
            f'        response->addHeader("Content-Encoding", "gzip");\n'
            f'        response->addHeader("Cache-Control", "max-age=3600");\n'
            f'        request->send(response);\n'
            f'    }});'
        )

    lines.append("/**")
    lines.append(" * @brief Registers all static web application routes on the AsyncWebServer.")
    lines.append(" */")
    lines.append("inline void register_web_app_routes(AsyncWebServer *server) {")
    lines.append("    if (!server) return;")
    lines.extend(route_registrations)
    lines.append("}")
    lines.append("")
    lines.append("#endif // WEB_SERVER_CONTENT_H")
    lines.append("")

    OUTPUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_HEADER.write_text("\n".join(lines), encoding="utf-8")
    print(f"Successfully generated {OUTPUT_HEADER} ({len(ASSETS)} assets embedded)")
    return 0


if __name__ == "__main__":
    exit(main())
